# Generated by Django 6.0.1 on 2026-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
